### ISSUE TITLE
New CLI options

### ISSUE THREAD

**Issue by eBardX** [waldoapp/waldo-go-cli#1]
Recognized options:

- `--git_branch` — The name of the branch for the commit.
- `--git_commit` — The hash of the originating commit on the (possibly remote) repository that triggered this upload. This is where we will post back a commit status (if the appropriate integration is configured).
- `--upload_token` — [Required unless implicitly provided by `WALDO_UPLOAD_TOKEN` environment variable.]
- `--variant_name` — Arbitrary user-generated identifier for this kind of binary (whatever this might mean). [Remove support for `WALDO_VARIANT_NAME` environment variable.]

For the two git options, we should honor explicit over implicit — trust the user if they specify a value explicitly (but also infer a value just in case).

Recognized query item names:

- `agentName=Waldo` — 
- `agentVersion=<x.y.z>` — 
- `arch=<arm64|x86_64>` — machine architecture detected by us
- `ci=<name>` — name of CI detected by us
- `flavor=<Android|iOS>` —
- `gitAccess=<noGitCommandFound|notGitRepository|ok>` — able to access git?
- `gitBranch=<name>` — git branch name inferred by us
- `gitCommit=<hash>` — git commit hash inferred by us
- `platform=<Linux|macOS|Windows>` — platform detected by us
- `userGitBranch=<name>` — git branch name passed in via `--git_branch` option
- `userGitCommit=<hash>` — git commit hash passed in via `--git_commit` option
- `variantName=<name>` — variant name passed in via `--variant_name` option
- `wrapperName=<Bitrise Step|Fastlane Plug-in|Go CLI>` —
- `wrapperVersion=<x.y.z>` —

Remove all symbols support and much of git history support.

Keep current `User-Agent` header for now for backward compatibility.

**Comment by laurentsigal** [comment]
@eBardX it should be all good now
