### ISSUE TITLE
Add retry to all calls that can have transient errors

### ISSUE THREAD

**Issue by eBardX** [waldoapp/waldo-go-cli#13]
Should we also add retries to waldo-go-agent?

**Comment by laurentsigal** [comment]
anything that does network calls should have retries. For reference, this was detected because we got a network error while fetching the new agent from github API

**Comment by eBardX** [comment]
@laurentsigal 

I’m thinking of handling HTTP status codes as follows:

- `1xx` — failure (since we are not expecting any of these and would not be able to properly handle them)
- `2xx` — success
- `3xx` — failure (if not handled by underlying network code)
- `4xx` — failure
- `5xx` — retry (1x)

Does this seem reasonable to you?

**Comment by eBardX** [comment]
Also, if the agent encounters a transient error (and has not yet retried the request), should it upload the error to the backend or should it upload the error if it is out of retries?

**Comment by laurentsigal** [comment]
It is super important to retry on all requests that abort without an error code (I would say any of them). In our case, limiting to those + all 5xx should be enough.
But if you do the curl convention that's also good.

As for error reporting, just report when you're out of retries.
Finally (in favor of using curl convention) you should also retry around the fetch of waldo-agent. I had one instance where github failed to serve it, and I had to re-run `waldo upload xxx`

**Comment by eBardX** [comment]
Oh yes. I’ve already started adding retry logic to waldo-go-cli (for the agent download) and the Bitrise custom step (for same), as well as go waldo-go-agent (for the actual upload). I suppose I’ll have to do likewise for the fastlane plug-in (but not happily).
