### ISSUE TITLE
Enhance support for `waldo upload`

### ISSUE THREAD

**Issue by edelans** [waldoapp/waldo-go-cli#23]
## `waldo upload`

Uploads a build to Waldo.

<aside>
⚠️ This command is a bit tricky because we *must not* break existing customer CI usage of this command.

</aside>

The current command syntax is as follows:

```
USAGE: waldo upload [--git_branch <b>] [--git_commit <c>] [--help] [--upload_token <t>] [--variant_name <n>] [--verbose] [] <build-path>

ARGUMENTS:
  <build-path>            The path to your build ('.app' or '.apk').

OPTIONS:
  --git_branch <b>        The originating git commit branch name.
  --git_commit <c>        The originating git commit hash.
  --help                  Display available options and exit.
  --upload_token <t>      The upload token associated with your app.
  --variant_name <n>      An optional variant name.
  --verbose               Display extra verbiage.
  --version               Display version and exit.
```

The proposed command syntax is as follows:

```
USAGE: waldo upload [--git_branch <b>] [--git_commit <c>] [--upload_token <t>] [--variant_name <n>] [--verbose] [<build-path>]

ARGUMENTS:
  <build-path>            The path to your build ('.app' or '.apk').

OPTIONS:
  --git_branch <b>        The originating git commit branch name.
  --git_commit <c>        The originating git commit hash.
  --upload_token <t>      The upload token associated with your app.
  --variant_name <n>      An optional variant name.
  --verbose               Display extra verbiage.
```

### Actions

- Determines if the command is executing in a CI environment (by checking the `CI` environment variable). If so, consider the command to be “in CI mode”; otherwise, consider the command to be “interactive”.
- If in CI mode:
    - Download the latest available Waldo Upload Agent into a temporary location.
    - Check that the `<build-path>` argument is specified and is valid (relatively speaking).
    - Obtain the upload token from either the `--upload_token` option or the `WALDO_UPLOAD_TOKEN` environment variable. The option takes precedence over the environment variable.
- If interactive:
    - (Handles the upload directly — no agent necessary.)
    - If the `<build-path>` argument is *not* specified, determine the most recent build from the user-specific data.
    - Obtain the upload token from `./.waldo/config.yml`. Fail if the `--upload_token` option is specified.
- Perform the actual upload.

**Comment by VincentJaouen** [comment]
We should keep in mind that we need to somehow get the appVersionId from the output (stdout, generated file?)

**Comment by eBardX** [comment]
Is that the exact name of the response payload field (`appVersionId`) that you need? If there is other info you will need, let me know sooner rather than later.

**Comment by VincentJaouen** [comment]
We would need the `id` property of the payload response from API
